### ISSUE TITLE
Can't rerun your work -- no such module 'r_bleu'

### ISSUE THREAD

**Issue by AftabHussain** [Lyz1213/Backdoored_PPLM#1]
Dear Backdoored_PPLM Team, ran into the following issue, 
was not able to find any resolution for the following missing module, -- there does not seem to exist any such module --appreciate your help.

```
machine: Backdoored_PPLM/code2code# source runt.sh 
NODE_INDEX: 0
PER_NODE_GPU: 4
NUM_NODE: 1
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    from r_bleu import _bleu
ModuleNotFoundError: No module named 'r_bleu'
```

**Comment by Lyz1213** [comment]
Thanks for your message. We've pushed this module to this repo.
