### ISSUE TITLE
About CodeT5

### ISSUE THREAD

**Issue by Kiki2049** [Lyz1213/Backdoored_PPLM#2]
Hi, Great Work!

I noticed that you did not open source the code of the attack process and the code related to CodeT5. Will these be made public?

In addition, CodeT5 doesn't seem to expose the pre-training code, have you re-implemented the process?

**Comment by Lyz1213** [comment]
Thank you very much for your message. I'm sorry that we haven't pushed the code related to pre-train yet. We will sort out the code and add new modules in the near future.
