### ISSUE TITLE
Key Mismatch error while loading checkpoint in text2code BART Model 

### ISSUE THREAD

**Issue by nitesh31mishra** [Lyz1213/Backdoored_PPLM#3]
I tried to implement the text2code module. I have used the checkpoint provided in the README file, and BART model as MODEL_TYPE. However, I am getting the key Mismatch error when loading the model on this line in` run.py` file:    
`model.load_state_dict(torch.load(output_dir))`   

Here, output_dir consist of pytorch_model.bin file provided as Checkpoint.

Error looks like

> Missing key(s) in state_dict: "model.final_logits_bias", "model.model.shared.weight", "model.model.encoder.embed_tokens.weight",.....
> Unexpected key(s) in state_dict: "final_logits_bias", "lm_head.weight", "model.shared.weight", "model.encoder.embed_tokens.weight",.....,

I noticed that, all the keys in your checkpoint and what BART expects is `model.` before each of them.   

Issue might be in the architecture while training and current BART model architecture provided in the file. Or is there something else I am missing to configure??   

Any idea on how to resolve this?

 Thanks for your amazing work!

**Comment by Lyz1213** [comment]
Thank you very much for your interest and inquiry. It seems that the error you encountered mainly stems from directly specifying our provided pre-trained model as the test path. In fact, you should first set the test_path argument to None, enter the fine-tuning mode, and fine-tune the pre-trained model for the specific downstream task. Then, you can set the test_path to the path where you have saved the model for testing.
